name: Clang Format Checker
on: push
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: RafikFarhad/clang-format-github-action@v6
        with:
          sources: "src/*.h,examples/**/*.ino"
          style: file